### PR TITLE
Enable Next Hold and Back Hold Buttons

### LINKED ISSUE #71: Logitech Spotlight do not send next and back hold events
The device by default do not seem to send any event on either of Next or Back hold event.

I guess on windows official software do some kind of initialization of device and then the device starts to send such events.

However, I am not able to find the required usb packets.

### LINKED ISSUE #85: Feature Request: Scroll on button hold
Hi, let me first thank you for making this software. I recently made the switch to Linux and not being able to use my Spotlight was one of the last things holding me back. So thanks for solving that issue!

One feature of the official software is that you can scroll by holding down a button (I don't remember which one, or if it is configurable) and rotating the presenter up and down to scroll. This allows you to quickly scroll through a lot of slides. I have no idea if this implementable with the new button mapping framework.

### PR DESCRIPTION
**Pull request by mayanksuman**
This PR configures the Spotlight device to send next and back hold events (as HID++ communication, hence, fixes #71 ).

New Actions (like Scroll Horizontal, Scroll Vertical and Change Volume) are introduced to take the advantage of these new 'hold' event (hence, fixes #85 ).

Fixes #71 , #85

### CODE REVIEW

**Comment by jahnf** [comment]
Hi @mayanksuman  thanks for this 👍, unfortunately we have created changes at the same time as I was still trying to refactor out the hid++ functionality. I'll try to integrate this PR. It will take me a week as I don't have too much free time currently beside the day to day job

**Comment by mayanksuman** [comment]
> unfortunately we have created changes at the same time as I was still trying to refactor out the hid++ functionality. 

No issue.
(@jahnf ) After the refactor of hid++ functionality you can push your changes to your `feature/spotlight-hidraw-functionality` branch. I can then rebase this PR to those changes.

**Comment by jahnf** [comment]
> No issue.
>..... I can then rebase this PR to those changes.

Thank for the offer, but I suspect that rebasing on those changes will be quiet some work - If you don't have any additions to this PR for now, I will base my refactoring on your changes here 👍 - and then we can fine tune and of course testing before it goes to develop. Let me know when I can merge and base the refactoring on that.

**Comment by mayanksuman** [comment]
Yes, you can merge. The work on this PR is complete.

However, please note that in commit c0ac8d4d329ca9049e93560e31950c2d8dcd30f5, Action struct in deviceinput.h has changed
so configuration files saved by earlier version of Projecteur might be invalid. If configuration file created by earlier version of Projecteur exist, new version of Projecteur may SegFault. To correct this issue, delete the earlier configuration. For Debian based system the configuration file is saved in ~/.config/Projecteur directory. For other systems please check https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes.

**Comment by jahnf** [comment]
> Yes, you can merge. The work on this PR is complete.
> 
> However, please note that in commit [c0ac8d4](https://github.com/jahnf/Projecteur/commit/c0ac8d4d329ca9049e93560e31950c2d8dcd30f5), Action struct in deviceinput.h has changed so configuration files saved by earlier version of Projecteur might be invalid. If configuration file created by earlier version of Projecteur exist, new version of Projecteur may SegFault. To correct this issue, delete the earlier configuration. For Debian based system the configuration file is saved in ~/.config/Projecteur directory. For other systems please check https://doc.qt.io/qt-5/qsettings.html#platform-specific-notes.

I see what you mean - will fix it together with my other restructure changes. // as mentioned earlier - will be hopefully sometimes during this week.

**Comment by mayanksuman** [comment]
Hi @jahnf , 

I have fixed the merge conflicts due to recent PR #147.

Additionally, I have refactored the code so that Projecteur do not SegFault due to older version of configuration.

Hence, Projecteur is able to load the configuration from previous version with any issue.

**Pull request merged**
