### PR TITLE
Pointer mode (Zoom) changes on double click

### PR DESCRIPTION
**Pull request by mayanksuman**
The Zoom is toggled if user double tap the pointer (top most) button (within 300ms; can be changed as it is part of Setting).

A major redesign of events handling has occurred. As it was necessary that the double click (and associated two clicks) events should not be passed to presentation so projecteur now grabs the input from SpotLight device. However, all other events (except Mouse Click) is passed again to the system by using uinput interface. The current redesign can help in giving solution to #43 without using a custom bash script.

Double Click is not passed to system rather used for changing the mode of presenter (toggling Zoom Setting). This is same behaviour as official software.

### CODE REVIEW

**Comment by jahnf** [comment]
Cool, I'll have a look later.

**Comment by jahnf** [comment]
I'll merge to the feature branch later. would you like to squash your 17 commits on your side to 1 or 2 commits before I do that or would you like to keep them as they are?

**Comment by mayanksuman** [comment]
Yes. As it is logically one feature change, so I will squash them into one commit.

**Comment by jahnf** [comment]
Thanks, 
after I merge to the `feature/pointer-mode-uinput-dev` branch tonight,
please allow me some time (_**up to a week** I guess_) to make some tests and code cleanup/bug fixes where necessary before the changes get into develop.
Although I am quick to respond on github, I don't have much time to code and test too much currently

**Comment by jahnf** [comment]
I guess now you see the point why I am hesitant to just merge to develop - you are making a lot of changes _after_ your initial pull request and I am sure there are still more isses :wink:

**Comment by mayanksuman** [comment]
I encountered the issue that the `uinput` device was not getting created on one of my machine. Then I checked for `udev` configuration differences between machines.

I guess there is no more issues left. We can keep it in feature branch and test it for some more days before merging it into `develop`.

**Pull request merged**
