### PR TITLE
Feature: User-friendly name in Input Mapper

### PR DESCRIPTION
**Pull request by mayanksuman**
The Input sequence is now drawn with meaningful text. The screenshot of
input mapper button mapping is also updated in this commit.

Screenshot: name of Input Sequence.
screenshot-button-mapping

### CODE REVIEW

**Comment by mayanksuman** [comment]
Hi @jahnf , 

The changes for this feature is over. You can now review this commit.

**Comment by jahnf** [comment]
Hi @mayanksuman , good idea.
The only thing I want to change is that the name replacement for 'next' and 'back' button should be Logitech Spotlight specific.
Other devices might send a BTN_RIGHT event but the button on the device is not called 'next'.

**Comment by mayanksuman** [comment]
Hi @jahnf , 

Can we rename `Next` and `Back` to `Right` and `Left`. This way it will be universal. However, we may need to mention in docs that `Right` and `Left` mean `Next` and `Back` respectively for Logitech Spotlight device.

**Comment by jahnf** [comment]
> Hi @jahnf ,
> 
> Can we rename `Next` and `Back` to `Right` and `Left`, respectively. This way it will be universal. However, we may need to mention in docs that `Right` and `Left` mean `Next` and `Back` respectively for Logitech Spotlight device.

Actually I meant it the other way `[Next]` and `[Back]` is good for the specified button combinations, but only for the Logitech spotlight - so the only thing I will add is a lookup table for user friendly button names that is device specific.

**Pull request merged**
