### PR TITLE
Automatically preset loading

### PR DESCRIPTION
**Pull request by mayanksuman**
This pull request ensure that setting belong to selected preset. It avoid an issue with cycle preset setting. Sometimes the selected preset is different than setting (upon program start) creating confusion while cycling preset.

### CODE REVIEW

**Comment by jahnf** [comment]
I get your idea, but currently a preset is currently basically a static set of settings stored away, and totally independent from the current settings. I agree that this is a little bit confusing - I need think about how this can be combined - so that it's not confusing to the user.

Btw: Your changes do not work: for example if you try to create a new preset.., and it is even more confusing, because the user is under the impression the current view represents the current preset which it is not..

**Comment by mayanksuman** [comment]
> if you try to create a new preset.., and it is even more confusing, because the user is under the impression the current view represents the current preset which it is not..

Yeah, that is the shortcoming right now. I was thinking of making the combobox empty, when any new setting change is done.

**Comment by jahnf** [comment]
> Yeah, that is the shortcoming right now. I was thinking of making the combobox empty, when any new setting change is done.

Yes that could be an idea that could work.

but also creating new presets does not really work with your current change anymore. When I tested it - made changes to the current settings and then created new preset -- my changes are gone.

I would rather test it and play with some ideas on a branch than putting it directly to develop.
There might be side effects

**Comment by jahnf** [comment]
I will open a branch, there we can test some more.
After these changes - I will keep the develop unchanged for a while - open only for bug fixes. I like to release a version 0.8 end of June.

**Comment by jahnf** [comment]
Could you please change this pull request to: feature/preset-behavior-improvement ?
I can then merge your changes and check for side effects and mitigation.

**Comment by mayanksuman** [comment]
> Could you please change this pull request to: feature/preset-behavior-improvement ?

I have already made a pull request. Closing this one.

**Pull request closed without merging**
