### PR TITLE
X1mouse

### PR DESCRIPTION
**Pull request by dbrandonjohnson**
Adds the X1 Presenter Mouse as a supported device using USB or Bluetooth

### CODE REVIEW

**Comment by jahnf** [comment]
Cool, thanks a lot.  I still have one question: The X1 Presenter Mouse is a device one can use as a regular mouse and as a presenter as I understand. I guess mouse move events will trigger the spotlight, even if used as a 'normal' mouse (and if Projecteur is running) - is that correct?

**Comment by dbrandonjohnson** [comment]
That is one issue you need to turn off Projector to use it as a standalone mouse.

This is how it appears in DMESG

```
[ 8491.864047] input: ThinkPad X1 Presenter Mouse as /devices/virtual/misc/uhid/0005:17EF:60DB.0015/input/input72
[ 8491.865259] input: ThinkPad X1 Presenter Mouse Keypad as /devices/virtual/misc/uhid/0005:17EF:60DB.0015/input/input73
[ 8491.865691] input: ThinkPad X1 Presenter Mouse Consumer Control as /devices/virtual/misc/uhid/0005:17EF:60DB.0015/input/input74
```

There might be a way to distinguish between mouse mode and presenter mode but I haven't had time to dig into that further.  It does trigger a keypress of a non-standard key when you press a button that looks like a "laser pointer"

**Comment by jahnf** [comment]
So when you have the device in "presenter" mode, does the mouse pointer only move when you press the "laser pointer" button?

And is it possible to record that button press in Projecteur's device tab (input map)?

I am thinking about implementing/adding an additional action, that a user could map then to some input sequence, that toggles (enables/disables) the "spotlight" on mouse move events.

**Comment by dbrandonjohnson** [comment]
Yes in presenter mode the mouse only moves when you push that button.  The keycode is 248.

**Comment by jahnf** [comment]
Thanks. When implementing the action to toggle the spot completely on/off I'll notify you so you can test it if that's okay!?

**Comment by dbrandonjohnson** [comment]
That is awesome, Thanks @jahnf!

**Pull request merged**
